//! The words of the upload checks and explanations in the window's languages. English is `stl_core::uploadcheck::english` (one source for
//! the window, the command line and the reports); here are the other eight, in the order 简体, 繁體, 日本語, 한국어, Deutsch, Français,
//! Español, Русский. A test checks every key has all eight with the same `{0}`, `{1}`… as the English.

use crate::i18n::Lang;
use stl_core::uploadcheck;

type Row = (&'static str, [&'static str; 8]);

const T: &[Row] = &[
    // ---- checks
    ("pf.content_missing", ["内容文件夹 {0} 不存在。", "內容資料夾 {0} 不存在。", "コンテンツフォルダー {0} がありません。", "콘텐츠 폴더 {0}이(가) 없습니다.", "Der Inhaltsordner {0} existiert nicht.", "Le dossier de contenu {0} n'existe pas.", "La carpeta de contenido {0} no existe.", "Папка содержимого {0} не существует."]),
    ("pf.content_empty", ["内容文件夹里没有文件：Steam 不接受空模组。", "內容資料夾裡沒有檔案：Steam 不接受空模組。", "コンテンツフォルダーにファイルがありません。空のMODはSteamに受け付けられません。", "콘텐츠 폴더에 파일이 없습니다. Steam은 빈 모드를 받지 않습니다.", "Der Inhaltsordner ist leer: Steam nimmt keine leeren Mods an.", "Le dossier de contenu est vide : Steam refuse les mods vides.", "La carpeta de contenido está vacía: Steam no acepta mods vacíos.", "Папка содержимого пуста: Steam не принимает пустые моды."]),
    ("pf.summary", ["将上传 {0} 个文件，共 {1}。", "將上傳 {0} 個檔案，共 {1}。", "{0} 個のファイル（{1}）をアップロードします。", "파일 {0}개({1})를 업로드합니다.", "{0} Dateien, {1} werden hochgeladen.", "{0} fichiers, {1} seront envoyés.", "Se subirán {0} archivos, {1}.", "Будет загружено файлов: {0}, {1}."]),
    ("pf.excluded", ["已自动排除 {0} 个文件或文件夹（{1}）：{2}。它们是版本管理、源素材、压缩包或系统文件；你的模组文件夹不会被改动。", "已自動排除 {0} 個檔案或資料夾（{1}）：{2}。它們是版本控制、原始素材、壓縮檔或系統檔；你的模組資料夾不會被改動。", "{0} 個のファイル・フォルダー（{1}）を自動で除外します：{2}。バージョン管理・素材・アーカイブ・システムファイルです。MODフォルダー自体は変更しません。", "파일/폴더 {0}개({1})를 자동으로 제외합니다: {2}. 버전 관리, 원본 소스, 압축 파일, 시스템 파일입니다. 모드 폴더는 바뀌지 않습니다.", "{0} Dateien oder Ordner ({1}) werden nicht hochgeladen: {2}. Versionsverwaltung, Quellgrafiken, Archive oder Systemdateien; dein Mod-Ordner bleibt unverändert.", "{0} fichiers ou dossiers ({1}) sont exclus de l'envoi : {2}. Gestion de versions, sources graphiques, archives ou fichiers système ; votre dossier n'est pas modifié.", "Se excluyen {0} archivos o carpetas ({1}): {2}. Control de versiones, archivos fuente, comprimidos o del sistema; tu carpeta no cambia.", "Исключено файлов и папок: {0} ({1}): {2}. Это контроль версий, исходники, архивы или системные файлы; папка мода не меняется."]),
    ("pf.long_paths", ["模组里有 {0} 个路径超过 180 个字符（例如 {1}）：订阅者的 Windows 可能无法解压。请缩短文件夹或文件名。", "模組裡有 {0} 個路徑超過 180 個字元（例如 {1}）：訂閱者的 Windows 可能無法解壓。請縮短資料夾或檔名。", "180文字を超えるパスが {0} 個あります（例：{1}）。購読者のWindowsで展開できない場合があります。名前を短くしてください。", "180자를 넘는 경로가 {0}개 있습니다(예: {1}). 구독자의 Windows에서 풀지 못할 수 있으니 이름을 줄이세요.", "{0} Pfade im Mod sind länger als 180 Zeichen (z. B. {1}): Windows kann sie bei Abonnenten evtl. nicht entpacken. Namen kürzen.", "{0} chemins dépassent 180 caractères (ex. {1}) : Windows peut échouer à les extraire chez les abonnés. Raccourcissez les noms.", "{0} rutas superan 180 caracteres (p. ej. {1}): Windows puede no extraerlas a los suscriptores. Acorta los nombres.", "Путей длиннее 180 символов: {0} (напр. {1}): у подписчиков Windows может не распаковать их. Сократите имена."]),
    ("pf.big", ["模组有 {0}：大文件上传更慢、更容易失败，请确认没有误放进去的东西。", "模組有 {0}：大檔案上傳較慢、較易失敗，請確認沒有誤放的東西。", "MODのサイズは {0} です。大きいほど時間がかかり失敗しやすくなります。不要なものがないか確認してください。", "모드 크기가 {0}입니다. 클수록 오래 걸리고 실패하기 쉽습니다. 실수로 넣은 파일이 없는지 확인하세요.", "Der Mod ist {0} groß: große Uploads dauern lange und scheitern öfter; prüfe, dass nichts versehentlich darin ist.", "Le mod fait {0} : les gros envois sont longs et échouent plus souvent ; vérifiez qu'il ne contient rien par erreur.", "El mod ocupa {0}: las subidas grandes tardan y fallan más; revisa que no haya nada por error.", "Размер мода {0}: большие загрузки долги и чаще срываются; проверьте, нет ли лишнего."]),
    ("pf.descriptor_missing", ["内容文件夹里没有 descriptor.mod：订阅者的启动器和游戏要从它读取模组名称和版本。", "內容資料夾裡沒有 descriptor.mod：訂閱者的啟動器和遊戲要從它讀取模組名稱和版本。", "コンテンツフォルダーに descriptor.mod がありません。購読者のランチャーとゲームはここからMOD名とバージョンを読みます。", "콘텐츠 폴더에 descriptor.mod가 없습니다. 구독자의 런처와 게임은 여기서 이름과 버전을 읽습니다.", "Im Inhaltsordner fehlt descriptor.mod: Launcher und Spiel der Abonnenten lesen daraus Name und Version.", "Il n'y a pas de descriptor.mod dans le dossier de contenu : le lanceur et le jeu des abonnés y lisent nom et version.", "Falta descriptor.mod en la carpeta de contenido: el lanzador y el juego de los suscriptores leen de ahí nombre y versión.", "В папке содержимого нет descriptor.mod: лаунчер и игра подписчиков берут из него имя и версию."]),
    ("pf.descriptor_differs", ["内容文件夹里的 descriptor.mod 与 mod 文件夹中的 .mod 文件这几项不一致：{0}。订阅者拿到的是内容文件夹里的那份。", "內容資料夾裡的 descriptor.mod 與 mod 資料夾中的 .mod 檔這幾項不一致：{0}。訂閱者拿到的是內容資料夾裡那份。", "コンテンツ内の descriptor.mod と mod フォルダーの .mod で次が一致しません：{0}。購読者に届くのはコンテンツ内の方です。", "콘텐츠의 descriptor.mod와 mod 폴더의 .mod가 다릅니다: {0}. 구독자는 콘텐츠 쪽을 받습니다.", "descriptor.mod im Inhaltsordner und die .mod-Datei im mod-Ordner unterscheiden sich bei: {0}. Abonnenten bekommen die aus dem Inhaltsordner.", "Le descriptor.mod du contenu et le fichier .mod du dossier mod diffèrent sur : {0}. Les abonnés reçoivent celui du contenu.", "descriptor.mod del contenido y el .mod de la carpeta mod difieren en: {0}. Los suscriptores reciben el del contenido.", "descriptor.mod в содержимом и .mod в папке mod расходятся в: {0}. Подписчики получат тот, что в содержимом."]),
    ("pf.remote_id_differs", ["两个描述文件指向不同的创意工坊条目（{0} 和 {1}）：将上传到 {0}。", "兩個描述檔指向不同的工作坊項目（{0} 和 {1}）：將上傳到 {0}。", "2つの descriptor が別のアイテムを指しています（{0} と {1}）。{0} にアップロードします。", "두 디스크립터가 다른 항목을 가리킵니다({0}, {1}). {0}에 업로드합니다.", "Die beiden Beschreibungen nennen verschiedene Workshop-Einträge ({0} und {1}): hochgeladen wird zu {0}.", "Les deux descripteurs visent des objets différents ({0} et {1}) : l'envoi va vers {0}.", "Los dos descriptores apuntan a objetos distintos ({0} y {1}): se sube a {0}.", "Дескрипторы указывают на разные предметы ({0} и {1}): загрузка пойдёт в {0}."]),
    ("pf.picture_missing", ["描述文件指定的图片 {0} 不在内容文件夹里。", "描述檔指定的圖片 {0} 不在內容資料夾裡。", "descriptor が指定する画像 {0} がコンテンツフォルダーにありません。", "디스크립터가 지정한 그림 {0}이(가) 콘텐츠 폴더에 없습니다.", "Die Beschreibung nennt das Bild {0}, das im Inhaltsordner fehlt.", "Le descripteur nomme l'image {0}, absente du dossier de contenu.", "El descriptor nombra la imagen {0}, que no está en el contenido.", "Дескриптор указывает картинку {0}, которой нет в содержимом."]),
    ("pf.no_supported_version", ["描述文件没有 supported_version：游戏会把模组标为「为其他版本制作」。", "描述檔沒有 supported_version：遊戲會把模組標為「為其他版本製作」。", "descriptor に supported_version がありません。ゲームは別バージョン用と表示します。", "디스크립터에 supported_version이 없어 게임이 다른 버전용으로 표시합니다.", "Die Beschreibung hat kein supported_version: das Spiel zeigt den Mod als für eine andere Version gemacht.", "Le descripteur n'a pas de supported_version : le jeu marquera le mod comme fait pour une autre version.", "El descriptor no tiene supported_version: el juego marcará el mod como de otra versión.", "В дескрипторе нет supported_version: игра пометит мод как сделанный для другой версии."]),
    ("pf.bad_supported_version", ["supported_version「{0}」不是游戏认识的格式（例如 v4.5.*）。", "supported_version「{0}」不是遊戲認得的格式（例如 v4.5.*）。", "supported_version「{0}」はゲームが理解する形式（v4.5.* など）ではありません。", "supported_version \"{0}\"은(는) 게임이 이해하는 형식(v4.5.* 등)이 아닙니다.", "supported_version „{0}“ hat nicht die Form, die das Spiel versteht (wie v4.5.*).", "supported_version « {0} » n'a pas la forme comprise par le jeu (comme v4.5.*).", "supported_version «{0}» no tiene la forma que entiende el juego (como v4.5.*).", "supported_version «{0}» не в понятном игре виде (например v4.5.*)."]),
    ("pf.title_empty", ["模组没有名称：Steam 需要标题。", "模組沒有名稱：Steam 需要標題。", "MOD名がありません。Steamにはタイトルが必要です。", "모드 이름이 없습니다. Steam에는 제목이 필요합니다.", "Der Mod hat keinen Namen: Steam braucht einen Titel.", "Le mod n'a pas de nom : Steam exige un titre.", "El mod no tiene nombre: Steam necesita un título.", "У мода нет названия: Steam нужен заголовок."]),
    ("pf.title_too_long", ["标题有 {0} 字节，Steam 最多接受 128 字节（按 UTF-8 计，一个汉字占 3 字节）。需要缩短 {1} 字节。", "標題有 {0} 位元組，Steam 最多接受 128 位元組（按 UTF-8 計，一個漢字占 3 位元組）。需要縮短 {1} 位元組。", "タイトルは {0} バイトです。Steamの上限は128バイト（UTF-8、漢字・かなは1文字3バイト）。{1} バイト短くしてください。", "제목이 {0}바이트입니다. Steam은 최대 128바이트(UTF-8, 한글은 3바이트)만 받습니다. {1}바이트 줄이세요.", "Der Titel hat {0} Bytes; Steam nimmt höchstens 128 (UTF-8-Bytes). Um {1} Bytes kürzen.", "Le titre fait {0} octets ; Steam en accepte 128 au plus (octets UTF-8). Raccourcissez-le de {1} octets.", "El título tiene {0} bytes; Steam acepta como máximo 128 (bytes UTF-8). Acórtalo {1} bytes.", "Заголовок — {0} байт; Steam принимает не больше 128 (байты UTF-8, кириллица по 2). Сократите на {1} байт."]),
    ("pf.note_too_long", ["更新说明有 {0} 字节，Steam 最多接受 8000 字节。需要缩短 {1} 字节。", "更新說明有 {0} 位元組，Steam 最多接受 8000 位元組。需要縮短 {1} 位元組。", "変更内容は {0} バイトです。上限は8000バイト。{1} バイト短くしてください。", "변경 사항이 {0}바이트입니다. 최대 8000바이트입니다. {1}바이트 줄이세요.", "Die Änderungsnotiz hat {0} Bytes; Steam nimmt höchstens 8000. Um {1} Bytes kürzen.", "La note de version fait {0} octets ; Steam en accepte 8000 au plus. Raccourcissez-la de {1} octets.", "La nota de cambios tiene {0} bytes; el máximo es 8000. Acórtala {1} bytes.", "Описание изменений — {0} байт; максимум 8000. Сократите на {1} байт."]),
    ("pf.description_too_long", ["简介有 {0} 字节，Steam 最多接受 8000 字节。需要缩短 {1} 字节。", "簡介有 {0} 位元組，Steam 最多接受 8000 位元組。需要縮短 {1} 位元組。", "説明は {0} バイトです。上限は8000バイト。{1} バイト短くしてください。", "설명이 {0}바이트입니다. 최대 8000바이트입니다. {1}바이트 줄이세요.", "Die Beschreibung hat {0} Bytes; Steam nimmt höchstens 8000. Um {1} Bytes kürzen.", "La description fait {0} octets ; Steam en accepte 8000 au plus. Raccourcissez-la de {1} octets.", "La descripción tiene {0} bytes; el máximo es 8000. Acórtala {1} bytes.", "Описание — {0} байт; максимум 8000. Сократите на {1} байт."]),
    ("pf.unknown_tags", ["这些标签不在群星创意工坊的标签列表里：{0}。Steam 可能拒绝，请使用模组表单里的标签。", "這些標籤不在群星工作坊的標籤列表中：{0}。Steam 可能拒絕，請使用模組表單裡的標籤。", "Stellaris ワークショップにないタグ：{0}。拒否される場合があるので、MODフォームのタグを使ってください。", "Stellaris 창작마당에 없는 태그: {0}. 거부될 수 있으니 모드 양식의 태그를 쓰세요.", "Tags, die der Stellaris-Workshop nicht anbietet: {0}. Steam lehnt sie evtl. ab; nimm die Tags aus dem Mod-Formular.", "Tags absents du Workshop de Stellaris : {0}. Steam peut les refuser ; utilisez ceux du formulaire.", "Etiquetas que el Workshop de Stellaris no ofrece: {0}. Steam puede rechazarlas; usa las del formulario.", "Теги, которых нет в мастерской Stellaris: {0}. Steam может их отклонить; используйте теги из формы мода."]),
    ("pf.no_preview_new", ["没有预览图（thumbnail.png）：新条目将没有图片。", "沒有預覽圖（thumbnail.png）：新項目將沒有圖片。", "プレビュー画像（thumbnail.png）がありません。新しいアイテムは画像なしになります。", "미리보기 그림(thumbnail.png)이 없어 새 항목에 그림이 없습니다.", "Kein Vorschaubild (thumbnail.png): der neue Eintrag hat kein Bild.", "Pas d'image d'aperçu (thumbnail.png) : le nouvel objet n'aura pas d'image.", "Sin imagen de vista previa (thumbnail.png): el nuevo objeto no tendrá imagen.", "Нет превью (thumbnail.png): у нового предмета не будет картинки."]),
    ("pf.keep_preview", ["这里没有预览图：条目会保留创意工坊上现有的图片。", "這裡沒有預覽圖：項目會保留工作坊上現有的圖片。", "ここにプレビュー画像がないため、ワークショップの現在の画像を使い続けます。", "여기에 미리보기가 없어 창작마당의 기존 그림을 유지합니다.", "Hier kein Vorschaubild: der Eintrag behält sein Bild im Workshop.", "Pas d'aperçu ici : l'objet garde son image du Workshop.", "Sin vista previa aquí: el objeto conserva su imagen del Workshop.", "Здесь нет превью: у предмета останется нынешняя картинка."]),
    ("pf.preview_missing", ["无法读取预览图 {0}。", "無法讀取預覽圖 {0}。", "プレビュー画像 {0} を読み込めません。", "미리보기 {0}을(를) 읽을 수 없습니다.", "Das Vorschaubild {0} lässt sich nicht lesen.", "L'aperçu {0} est illisible.", "No se puede leer la vista previa {0}.", "Не удаётся прочитать превью {0}."]),
    ("pf.preview_too_big", ["预览图 {0} 有 {1} KB，创意工坊只接受小于 1024 KB 的图片。请存小一些（JPG 或降低分辨率）。", "預覽圖 {0} 有 {1} KB，工作坊只接受小於 1024 KB 的圖片。請存小一些（JPG 或降低解析度）。", "プレビュー {0} は {1} KB です。1024 KB 未満にしてください（JPGにする、解像度を下げる）。", "미리보기 {0}이(가) {1} KB입니다. 1024 KB 미만이어야 합니다(JPG로 저장하거나 해상도를 낮추세요).", "Das Vorschaubild {0} hat {1} KB; der Workshop nimmt unter 1024 KB. Kleiner speichern (JPG oder weniger Pixel).", "L'aperçu {0} fait {1} Ko ; le Workshop exige moins de 1024 Ko. Enregistrez-le plus léger (JPG, moins de pixels).", "La vista previa {0} pesa {1} KB; el Workshop admite menos de 1024 KB. Guárdala más ligera (JPG o menos píxeles).", "Превью {0} — {1} КБ; нужно меньше 1024 КБ. Сохраните меньше (JPG или меньше пикселей)."]),
    ("pf.preview_format", ["预览图 {0} 不是 PNG、JPG 或 GIF（看起来是 {1}）：Steam 会拒绝。", "預覽圖 {0} 不是 PNG、JPG 或 GIF（看起來是 {1}）：Steam 會拒絕。", "プレビュー {0} は PNG・JPG・GIF ではありません（{1} のようです）。Steamに拒否されます。", "미리보기 {0}은(는) PNG, JPG, GIF가 아닙니다({1}로 보임). Steam이 거부합니다.", "Das Vorschaubild {0} ist kein PNG, JPG oder GIF (sieht nach {1} aus): Steam lehnt es ab.", "L'aperçu {0} n'est ni PNG, ni JPG, ni GIF (semble {1}) : Steam le refuse.", "La vista previa {0} no es PNG, JPG ni GIF (parece {1}): Steam la rechaza.", "Превью {0} не PNG, JPG или GIF (похоже на {1}): Steam его отклонит."]),
    ("pf.preview_ext", ["预览图 {0} 实际是 {1} 格式，与文件扩展名不符。Steam 通常能接受，但最好改成对应的扩展名。", "預覽圖 {0} 實際是 {1} 格式，與副檔名不符。Steam 通常能接受，但最好改成對應副檔名。", "プレビュー {0} の実際の形式は {1} で、拡張子と違います。通常は受け付けられますが、拡張子を直すと安全です。", "미리보기 {0}의 실제 형식은 {1}로 확장자와 다릅니다. 보통 받아들여지지만 확장자를 맞추는 것이 안전합니다.", "Das Vorschaubild {0} ist eigentlich {1}; die Dateiendung sagt etwas anderes. Meist klappt es, besser umbenennen.", "L'aperçu {0} est en fait un {1} ; son extension dit autre chose. Steam l'accepte souvent, renommez-le par prudence.", "La vista previa {0} es en realidad {1}; su extensión dice otra cosa. Suele aceptarse, pero renómbrala.", "Превью {0} на деле в формате {1}, а расширение другое. Обычно проходит, но лучше переименовать."]),
    ("pf.bad_item_id", ["「{0}」不是创意工坊条目编号（条目网址里 ?id= 后面的数字）。", "「{0}」不是工作坊項目編號（項目網址中 ?id= 後面的數字）。", "「{0}」はワークショップのアイテム番号（URLの ?id= の後の数字）ではありません。", "\"{0}\"은(는) 창작마당 항목 번호(주소의 ?id= 뒤 숫자)가 아닙니다.", "„{0}“ ist keine Workshop-Nummer (die Ziffern nach ?id= in der Adresse).", "« {0} » n'est pas un numéro d'objet (les chiffres après ?id= dans l'adresse).", "«{0}» no es un número de objeto (los dígitos tras ?id= en la dirección).", "«{0}» — не номер предмета (цифры после ?id= в адресе)."]),
    ("pf.steam_unavailable", ["无法连接 Steam：{0}", "無法連線 Steam：{0}", "Steamに接続できません：{0}", "Steam에 연결할 수 없습니다: {0}", "Steam ist nicht erreichbar: {0}", "Impossible de joindre Steam : {0}", "No se puede conectar con Steam: {0}", "Нет связи со Steam: {0}"]),
    ("pf.account", ["已登录的 Steam 账号：{0}。", "已登入的 Steam 帳號：{0}。", "Steamアカウント {0} でサインイン中。", "Steam 계정 {0}(으)로 로그인됨.", "Bei Steam angemeldet als Konto {0}.", "Connecté à Steam avec le compte {0}.", "Sesión de Steam con la cuenta {0}.", "Вход в Steam под учётной записью {0}."]),
    ("pf.item_not_visible", ["Steam 不公开显示条目 {0}：它是私密、仅好友可见，或已删除。如果已删除，上传会失败，请清空条目编号新建一个。", "Steam 不公開顯示項目 {0}：它是私人、僅好友可見或已刪除。若已刪除，上傳會失敗，請清空項目編號新建。", "アイテム {0} は公開表示されていません（非公開・フレンド限定・削除済み）。削除済みなら失敗するので、番号を消して新規作成してください。", "항목 {0}이(가) 공개로 보이지 않습니다(비공개·친구 공개·삭제). 삭제되었다면 실패하니 번호를 지우고 새로 만드세요.", "Steam zeigt Eintrag {0} nicht öffentlich: privat, nur Freunde oder gelöscht. Wenn gelöscht, scheitert der Upload; dann die Nummer leeren und neu anlegen.", "Steam n'affiche pas l'objet {0} publiquement : privé, amis seulement ou supprimé. S'il est supprimé, l'envoi échoue ; videz le numéro pour en créer un.", "Steam no muestra el objeto {0} públicamente: privado, solo amigos o borrado. Si se borró, la subida falla; vacía el número para crear uno nuevo.", "Steam не показывает предмет {0} публично: он скрыт, только для друзей или удалён. Если удалён — загрузка не пройдёт; очистите номер, чтобы создать новый."]),
    ("pf.item_other_game", ["条目 {0} 属于另一个游戏（应用 {1}），不是群星。", "項目 {0} 屬於另一個遊戲（應用程式 {1}），不是群星。", "アイテム {0} は Stellaris ではなく別のゲーム（アプリ {1}）のものです。", "항목 {0}은(는) Stellaris가 아닌 다른 게임(앱 {1})의 것입니다.", "Eintrag {0} gehört zu einem anderen Spiel (App {1}), nicht Stellaris.", "L'objet {0} appartient à un autre jeu (app {1}), pas à Stellaris.", "El objeto {0} es de otro juego (app {1}), no de Stellaris.", "Предмет {0} относится к другой игре (приложение {1}), не к Stellaris."]),
    ("pf.item_banned", ["条目 {0} 已被创意工坊封禁，无法更新。", "項目 {0} 已被工作坊封鎖，無法更新。", "アイテム {0} はワークショップで禁止されており、更新できません。", "항목 {0}은(는) 창작마당에서 차단되어 업데이트할 수 없습니다.", "Eintrag {0} ist im Workshop gesperrt und kann nicht aktualisiert werden.", "L'objet {0} est banni du Workshop ; il ne peut pas être mis à jour.", "El objeto {0} está bloqueado en el Workshop; no se puede actualizar.", "Предмет {0} заблокирован в мастерской; обновить нельзя."]),
    ("pf.item_other_owner", ["条目 {0} 由另一个账号（{1}）创建。只有对方把你加为贡献者，你才能更新它；否则 Steam 会返回「拒绝访问」。", "項目 {0} 由另一個帳號（{1}）建立。只有對方把你加為貢獻者，你才能更新它；否則 Steam 會回應「拒絕存取」。", "アイテム {0} は別のアカウント（{1}）が作成しました。所有者が協力者に追加していないと更新できず、「アクセス拒否」になります。", "항목 {0}은(는) 다른 계정({1})이 만들었습니다. 소유자가 기여자로 추가해야만 업데이트할 수 있고, 아니면 '접근 거부'가 납니다.", "Eintrag {0} stammt von einem anderen Konto ({1}). Aktualisieren geht nur, wenn der Besitzer dich als Mitwirkenden eingetragen hat; sonst antwortet Steam „Zugriff verweigert“.", "L'objet {0} a été créé par un autre compte ({1}). Vous ne pouvez le mettre à jour que si son propriétaire vous a ajouté comme contributeur ; sinon Steam répond « accès refusé ».", "El objeto {0} lo creó otra cuenta ({1}). Solo puedes actualizarlo si su dueño te añadió como colaborador; si no, Steam responde «acceso denegado».", "Предмет {0} создан другой учётной записью ({1}). Обновить его можно, только если владелец добавил вас в соавторы; иначе Steam ответит «доступ запрещён»."]),
    ("pf.item_info", ["创意工坊上：「{0}」，上次更新 {1}。", "工作坊上：「{0}」，上次更新 {1}。", "ワークショップ：「{0}」、最終更新 {1}。", "창작마당: \"{0}\", 마지막 업데이트 {1}.", "Im Workshop: „{0}“, zuletzt aktualisiert {1}.", "Sur le Workshop : « {0} », mis à jour le {1}.", "En el Workshop: «{0}», actualizado {1}.", "В мастерской: «{0}», обновлён {1}."]),
    // ---- explanations
    ("ex.headline", ["上传在{0}时中断。", "上傳在{0}時中斷。", "{0}の途中でアップロードが止まりました。", "{0} 중에 업로드가 멈췄습니다.", "Der Upload brach ab {0}.", "L'envoi s'est arrêté {0}.", "La subida se detuvo {0}.", "Загрузка остановилась {0}."]),
    ("ex.headline_status", ["上传在{0}（{1}）时中断。", "上傳在{0}（{1}）時中斷。", "{0}（{1}）の途中でアップロードが止まりました。", "{0}({1}) 중에 업로드가 멈췄습니다.", "Der Upload brach ab {0}, {1}.", "L'envoi s'est arrêté {0}, {1}.", "La subida se detuvo {0}, {1}.", "Загрузка остановилась {0}, {1}."]),
    ("ex.at_connect", ["启动 Steam", "啟動 Steam", "Steamの起動", "Steam 시작", "beim Starten von Steam", "au démarrage de Steam", "al iniciar Steam", "при запуске Steam"]),
    ("ex.at_create", ["创建创意工坊条目", "建立工作坊項目", "ワークショップアイテムの作成", "창작마당 항목 생성", "beim Anlegen des Workshop-Eintrags", "à la création de l'objet du Workshop", "al crear el objeto del Workshop", "при создании предмета мастерской"]),
    ("ex.at_start", ["打开条目准备更新", "開啟項目準備更新", "アイテムの更新開始", "항목 업데이트 시작", "beim Öffnen des Eintrags zum Aktualisieren", "à l'ouverture de l'objet pour la mise à jour", "al abrir el objeto para actualizarlo", "при открытии предмета для обновления"]),
    ("ex.at_title", ["设置标题", "設定標題", "タイトルの設定", "제목 설정", "beim Setzen des Titels", "en fixant le titre", "al poner el título", "при задании заголовка"]),
    ("ex.at_description", ["设置简介", "設定簡介", "説明の設定", "설명 설정", "beim Setzen der Beschreibung", "en fixant la description", "al poner la descripción", "при задании описания"]),
    ("ex.at_content", ["设置内容文件夹", "設定內容資料夾", "コンテンツフォルダーの設定", "콘텐츠 폴더 설정", "beim Setzen des Inhaltsordners", "en fixant le dossier de contenu", "al poner la carpeta de contenido", "при задании папки содержимого"]),
    ("ex.at_preview", ["设置预览图", "設定預覽圖", "プレビュー画像の設定", "미리보기 설정", "beim Setzen des Vorschaubilds", "en fixant l'aperçu", "al poner la vista previa", "при задании превью"]),
    ("ex.at_tags", ["设置标签", "設定標籤", "タグの設定", "태그 설정", "beim Setzen der Tags", "en fixant les tags", "al poner las etiquetas", "при задании тегов"]),
    ("ex.at_visibility", ["设置可见性", "設定可見性", "公開範囲の設定", "공개 범위 설정", "beim Setzen der Sichtbarkeit", "en fixant la visibilité", "al poner la visibilidad", "при задании видимости"]),
    ("ex.at_submit", ["发送更新", "傳送更新", "更新の送信", "업데이트 전송", "beim Senden des Updates", "à l'envoi de la mise à jour", "al enviar la actualización", "при отправке обновления"]),
    ("ex.status_config", ["准备条目设置", "準備項目設定", "設定の準備中", "설정 준비 중", "Einstellungen vorbereiten", "préparation des réglages", "preparando ajustes", "подготовка настроек"]),
    ("ex.status_preparing", ["准备文件", "準備檔案", "ファイル準備中", "파일 준비 중", "Dateien vorbereiten", "préparation des fichiers", "preparando archivos", "подготовка файлов"]),
    ("ex.status_content", ["上传文件", "上傳檔案", "ファイル送信中", "파일 업로드 중", "Dateien hochladen", "envoi des fichiers", "subiendo archivos", "загрузка файлов"]),
    ("ex.status_preview", ["上传预览图", "上傳預覽圖", "プレビュー送信中", "미리보기 업로드 중", "Vorschaubild hochladen", "envoi de l'aperçu", "subiendo la vista previa", "загрузка превью"]),
    ("ex.status_committing", ["提交新版本", "提交新版本", "新バージョンの確定中", "새 버전 확정 중", "neue Version festschreiben", "validation de la version", "confirmando la versión", "фиксация новой версии"]),
    ("ex.status_unknown", ["未知阶段", "未知階段", "不明な段階", "알 수 없는 단계", "in unbekannter Phase", "phase inconnue", "fase desconocida", "неизвестный этап"]),
    ("ex.no_steam", ["Steam API 没有启动。", "Steam API 沒有啟動。", "Steam API が起動しませんでした。", "Steam API가 시작되지 않았습니다.", "Die Steam-API startete nicht.", "L'API Steam n'a pas démarré.", "La API de Steam no se inició.", "Steam API не запустился."]),
    ("ex.no_answer", ["Steam 没有及时回应。", "Steam 沒有及時回應。", "Steamの応答がありませんでした。", "Steam이 제때 응답하지 않았습니다.", "Steam antwortete nicht rechtzeitig.", "Steam n'a pas répondu à temps.", "Steam no respondió a tiempo.", "Steam не ответил вовремя."]),
    ("ex.rejected_value", ["Steam 在发送任何内容之前就拒绝了这个值。", "Steam 在傳送任何內容之前就拒絕了這個值。", "送信前にSteamが値を拒否しました。", "전송 전에 Steam이 값을 거부했습니다.", "Steam lehnte den Wert ab, bevor etwas gesendet wurde.", "Steam a refusé la valeur avant tout envoi.", "Steam rechazó el valor antes de enviar nada.", "Steam отклонил значение до отправки."]),
    ("ex.code_fail", ["Steam 返回 {0}（{1}）：笼统的失败，没有说明原因。", "Steam 回應 {0}（{1}）：籠統的失敗，沒有說明原因。", "Steamの応答 {0}（{1}）：理由のない一般的な失敗です。", "Steam 응답 {0}({1}): 이유 없는 일반 실패입니다.", "Steam antwortete {0} ({1}): ein allgemeiner Fehler ohne Grund.", "Steam a répondu {0} ({1}) : un échec général, sans raison.", "Steam respondió {0} ({1}): un fallo general sin motivo.", "Steam ответил {0} ({1}): общий сбой без причины."]),
    ("ex.code_connection", ["Steam 返回 {0}（{1}）：与 Steam 服务器的连接失败。", "Steam 回應 {0}（{1}）：與 Steam 伺服器的連線失敗。", "Steamの応答 {0}（{1}）：Steamサーバーとの接続に失敗しました。", "Steam 응답 {0}({1}): Steam 서버 연결에 실패했습니다.", "Steam antwortete {0} ({1}): die Verbindung zu den Steam-Servern schlug fehl.", "Steam a répondu {0} ({1}) : la connexion aux serveurs de Steam a échoué.", "Steam respondió {0} ({1}): falló la conexión con sus servidores.", "Steam ответил {0} ({1}): не удалось соединиться с серверами Steam."]),
    ("ex.code_invalid_param", ["Steam 返回 {0}（{1}）：某个字段（标题、标签、说明、可见性）的值 Steam 不接受。", "Steam 回應 {0}（{1}）：某個欄位（標題、標籤、說明、可見性）的值 Steam 不接受。", "Steamの応答 {0}（{1}）：いずれかの項目（タイトル・タグ・変更内容・公開範囲）の値が受け付けられません。", "Steam 응답 {0}({1}): 제목·태그·변경 사항·공개 범위 중 하나의 값을 받지 않습니다.", "Steam antwortete {0} ({1}): ein Feld (Titel, Tags, Notiz, Sichtbarkeit) hat einen Wert, den Steam nicht annimmt.", "Steam a répondu {0} ({1}) : un champ (titre, tags, note, visibilité) a une valeur refusée.", "Steam respondió {0} ({1}): algún campo (título, etiquetas, nota, visibilidad) tiene un valor no aceptado.", "Steam ответил {0} ({1}): значение одного из полей (заголовок, теги, описание, видимость) не принимается."]),
    ("ex.code_file_not_found", ["Steam 返回 {0}（{1}）：找不到要发送的文件。", "Steam 回應 {0}（{1}）：找不到要傳送的檔案。", "Steamの応答 {0}（{1}）：送信するファイルが見つかりません。", "Steam 응답 {0}({1}): 보낼 파일을 찾을 수 없습니다.", "Steam antwortete {0} ({1}): eine zu sendende Datei wurde nicht gefunden.", "Steam a répondu {0} ({1}) : un fichier à envoyer est introuvable.", "Steam respondió {0} ({1}): no encontró un archivo que enviar.", "Steam ответил {0} ({1}): не найден файл для отправки."]),
    ("ex.code_busy", ["Steam 返回 {0}（{1}）：创意工坊正忙或暂时不可用。", "Steam 回應 {0}（{1}）：工作坊忙碌或暫時無法使用。", "Steamの応答 {0}（{1}）：ワークショップが混雑しているか一時的に使えません。", "Steam 응답 {0}({1}): 창작마당이 바쁘거나 일시적으로 사용할 수 없습니다.", "Steam antwortete {0} ({1}): der Workshop ist ausgelastet oder kurz nicht erreichbar.", "Steam a répondu {0} ({1}) : le Workshop est occupé ou indisponible.", "Steam respondió {0} ({1}): el Workshop está ocupado o no disponible.", "Steam ответил {0} ({1}): мастерская занята или временно недоступна."]),
    ("ex.code_duplicate_name", ["Steam 返回 {0}（{1}）：你已经有同名的创意工坊条目。", "Steam 回應 {0}（{1}）：你已經有同名的工作坊項目。", "Steamの応答 {0}（{1}）：同じ名前のアイテムが既にあります。", "Steam 응답 {0}({1}): 같은 이름의 항목이 이미 있습니다.", "Steam antwortete {0} ({1}): du hast schon einen Eintrag mit diesem Namen.", "Steam a répondu {0} ({1}) : vous avez déjà un objet de ce nom.", "Steam respondió {0} ({1}): ya tienes un objeto con ese nombre.", "Steam ответил {0} ({1}): у вас уже есть предмет с таким именем."]),
    ("ex.code_access_denied", ["Steam 返回 {0}（{1}）：拒绝访问。", "Steam 回應 {0}（{1}）：拒絕存取。", "Steamの応答 {0}（{1}）：アクセスが拒否されました。", "Steam 응답 {0}({1}): 접근이 거부되었습니다.", "Steam antwortete {0} ({1}): Zugriff verweigert.", "Steam a répondu {0} ({1}) : accès refusé.", "Steam respondió {0} ({1}): acceso denegado.", "Steam ответил {0} ({1}): доступ запрещён."]),
    ("ex.code_timeout", ["Steam 返回 {0}（{1}）：处理超时。", "Steam 回應 {0}（{1}）：處理逾時。", "Steamの応答 {0}（{1}）：時間切れです。", "Steam 응답 {0}({1}): 시간이 초과되었습니다.", "Steam antwortete {0} ({1}): es dauerte zu lange.", "Steam a répondu {0} ({1}) : délai dépassé.", "Steam respondió {0} ({1}): tardó demasiado.", "Steam ответил {0} ({1}): время истекло."]),
    ("ex.code_banned", ["Steam 返回 {0}（{1}）：此账号不能向这个游戏的创意工坊上传。", "Steam 回應 {0}（{1}）：此帳號不能向這個遊戲的工作坊上傳。", "Steamの応答 {0}（{1}）：このアカウントはこのゲームのワークショップにアップロードできません。", "Steam 응답 {0}({1}): 이 계정은 이 게임 창작마당에 업로드할 수 없습니다.", "Steam antwortete {0} ({1}): dieses Konto darf nicht in den Workshop dieses Spiels hochladen.", "Steam a répondu {0} ({1}) : ce compte ne peut pas publier dans le Workshop de ce jeu.", "Steam respondió {0} ({1}): esta cuenta no puede subir al Workshop de este juego.", "Steam ответил {0} ({1}): этой учётной записи нельзя загружать в мастерскую игры."]),
    ("ex.code_not_logged_on", ["Steam 返回 {0}（{1}）：Steam 客户端没有登录（或在别处登录了）。", "Steam 回應 {0}（{1}）：Steam 用戶端沒有登入（或在別處登入）。", "Steamの応答 {0}（{1}）：Steamクライアントがサインインしていません（または別の場所でサインイン）。", "Steam 응답 {0}({1}): Steam 클라이언트가 로그인되어 있지 않습니다(또는 다른 곳에서 로그인).", "Steam antwortete {0} ({1}): der Steam-Client ist nicht angemeldet (oder woanders).", "Steam a répondu {0} ({1}) : le client Steam n'est pas connecté (ou l'est ailleurs).", "Steam respondió {0} ({1}): el cliente de Steam no tiene sesión (o la abrió en otro lugar).", "Steam ответил {0} ({1}): клиент Steam не вошёл в аккаунт (или вошёл в другом месте)."]),
    ("ex.code_insufficient_privilege", ["Steam 返回 {0}（{1}）：此账号目前不允许上传。", "Steam 回應 {0}（{1}）：此帳號目前不允許上傳。", "Steamの応答 {0}（{1}）：このアカウントは現在アップロードできません。", "Steam 응답 {0}({1}): 이 계정은 지금 업로드할 수 없습니다.", "Steam antwortete {0} ({1}): dieses Konto darf gerade nicht hochladen.", "Steam a répondu {0} ({1}) : ce compte ne peut pas publier pour l'instant.", "Steam respondió {0} ({1}): esta cuenta no puede subir ahora.", "Steam ответил {0} ({1}): этой учётной записи сейчас нельзя загружать."]),
    ("ex.code_limit_exceeded", ["Steam 返回 {0}（{1}）：超出了某项限制。", "Steam 回應 {0}（{1}）：超出了某項限制。", "Steamの応答 {0}（{1}）：上限を超えました。", "Steam 응답 {0}({1}): 한도를 넘었습니다.", "Steam antwortete {0} ({1}): eine Grenze wurde überschritten.", "Steam a répondu {0} ({1}) : une limite est dépassée.", "Steam respondió {0} ({1}): se superó un límite.", "Steam ответил {0} ({1}): превышен лимит."]),
    ("ex.code_duplicate_request", ["Steam 返回 {0}（{1}）：这次上传已经完成过了。", "Steam 回應 {0}（{1}）：這次上傳已經完成過了。", "Steamの応答 {0}（{1}）：このアップロードは既に完了しています。", "Steam 응답 {0}({1}): 이미 업로드되었습니다.", "Steam antwortete {0} ({1}): das wurde schon hochgeladen.", "Steam a répondu {0} ({1}) : c'était déjà envoyé.", "Steam respondió {0} ({1}): ya se había subido.", "Steam ответил {0} ({1}): это уже загружено."]),
    ("ex.code_read_only", ["Steam 返回 {0}（{1}）：此账号暂时不能发布。", "Steam 回應 {0}（{1}）：此帳號暫時不能發佈。", "Steamの応答 {0}（{1}）：このアカウントは一時的に公開できません。", "Steam 응답 {0}({1}): 이 계정은 당분간 게시할 수 없습니다.", "Steam antwortete {0} ({1}): das Konto darf vorerst nicht veröffentlichen.", "Steam a répondu {0} ({1}) : le compte ne peut pas publier pour le moment.", "Steam respondió {0} ({1}): la cuenta no puede publicar por ahora.", "Steam ответил {0} ({1}): учётная запись временно не может публиковать."]),
    ("ex.code_disk_full", ["Steam 返回 {0}（{1}）：磁盘已满。", "Steam 回應 {0}（{1}）：磁碟已滿。", "Steamの応答 {0}（{1}）：ディスクがいっぱいです。", "Steam 응답 {0}({1}): 디스크가 가득 찼습니다.", "Steam antwortete {0} ({1}): ein Datenträger ist voll.", "Steam a répondu {0} ({1}) : un disque est plein.", "Steam respondió {0} ({1}): un disco está lleno.", "Steam ответил {0} ({1}): диск заполнен."]),
    ("ex.code_other", ["Steam 返回 {0}（{1}）。", "Steam 回應 {0}（{1}）。", "Steamの応答 {0}（{1}）。", "Steam 응답 {0}({1}).", "Steam antwortete {0} ({1}).", "Steam a répondu {0} ({1}).", "Steam respondió {0} ({1}).", "Steam ответил {0} ({1})."]),
    // ---- causes
    ("c.steam_not_running", ["Steam 没有运行、没有登录，或登录的账号没有群星。", "Steam 沒有執行、沒有登入，或登入的帳號沒有群星。", "Steamが起動していない、サインインしていない、またはStellarisを所有していないアカウントです。", "Steam이 실행 중이 아니거나, 로그인되지 않았거나, Stellaris가 없는 계정입니다.", "Steam läuft nicht, ist nicht angemeldet oder mit einem Konto ohne Stellaris.", "Steam n'est pas lancé, pas connecté, ou le compte ne possède pas Stellaris.", "Steam no está abierto, sin sesión, o la cuenta no tiene Stellaris.", "Steam не запущен, не вошёл в аккаунт или у аккаунта нет Stellaris."]),
    ("c.not_owner", ["条目 {0} 属于账号 {1}，当前登录的账号不是它的贡献者。", "項目 {0} 屬於帳號 {1}，目前登入的帳號不是它的貢獻者。", "アイテム {0} はアカウント {1} のもので、サインイン中のアカウントは協力者ではありません。", "항목 {0}은(는) 계정 {1}의 것이며 현재 계정은 기여자가 아닙니다.", "Eintrag {0} gehört Konto {1}, und das angemeldete Konto ist kein Mitwirkender.", "L'objet {0} appartient au compte {1}, et le compte connecté n'en est pas contributeur.", "El objeto {0} es de la cuenta {1} y la cuenta actual no es colaboradora.", "Предмет {0} принадлежит учётной записи {1}, а текущая не является соавтором."]),
    ("c.not_owner_unknown", ["条目 {0} 可能属于其他账号（Steam 不公开显示它的所有者）。", "項目 {0} 可能屬於其他帳號（Steam 不公開顯示所有者）。", "アイテム {0} は別のアカウントのものかもしれません（所有者は公開されていません）。", "항목 {0}이(가) 다른 계정의 것일 수 있습니다(소유자가 공개되지 않음).", "Eintrag {0} gehört evtl. einem anderen Konto (Steam zeigt den Besitzer nicht öffentlich).", "L'objet {0} appartient peut-être à un autre compte (propriétaire non public).", "El objeto {0} puede ser de otra cuenta (Steam no muestra su dueño).", "Предмет {0}, возможно, принадлежит другой учётной записи (владелец не публичен)."]),
    ("c.agreement", ["这个账号还没有接受 Steam 创意工坊法律协议。", "這個帳號還沒有接受 Steam 工作坊法律協議。", "このアカウントはSteamワークショップ法的同意書にまだ同意していません。", "이 계정은 아직 Steam 창작마당 법적 동의서에 동의하지 않았습니다.", "Dieses Konto hat die rechtliche Vereinbarung des Steam Workshop noch nicht angenommen.", "Ce compte n'a pas encore accepté l'accord juridique du Workshop Steam.", "Esta cuenta aún no aceptó el acuerdo legal del Workshop de Steam.", "Эта учётная запись ещё не приняла соглашение мастерской Steam."]),
    ("c.invalid_field", ["某个字段的值被 Steam 拒绝：太长、标签不存在，或含有它不接受的字符。", "某個欄位的值被 Steam 拒絕：太長、標籤不存在，或含有它不接受的字元。", "いずれかの値が拒否されました：長すぎる、存在しないタグ、使えない文字など。", "어떤 값이 거부되었습니다: 너무 길거나, 없는 태그거나, 받지 않는 문자가 있습니다.", "Ein Feld hat einen Wert, den Steam ablehnt: zu lang, ein unbekannter Tag oder unzulässige Zeichen.", "Un champ a une valeur refusée : trop longue, tag inconnu, ou caractères non acceptés.", "Un campo tiene un valor rechazado: muy largo, una etiqueta desconocida o caracteres no admitidos.", "Значение поля отклонено: слишком длинное, неизвестный тег или недопустимые символы."]),
    ("c.file_missing", ["上传途中内容文件夹或预览图被移动或删除，或者路径里有 Steam 打不开的字符。", "上傳途中內容資料夾或預覽圖被移動或刪除，或路徑中有 Steam 打不開的字元。", "アップロード中にフォルダーや画像が移動・削除されたか、パスにSteamが開けない文字があります。", "업로드 중 폴더나 미리보기가 옮겨지거나 지워졌거나, 경로에 Steam이 열 수 없는 문자가 있습니다.", "Inhaltsordner oder Vorschaubild wurden beim Hochladen verschoben oder gelöscht, oder der Pfad enthält Zeichen, die Steam nicht öffnen kann.", "Le dossier ou l'aperçu a été déplacé ou supprimé pendant l'envoi, ou le chemin contient des caractères que Steam ne sait pas ouvrir.", "La carpeta o la vista previa se movió o borró durante la subida, o la ruta tiene caracteres que Steam no abre.", "Папку или превью переместили или удалили во время загрузки, либо в пути есть символы, которые Steam не открывает."]),
    ("c.cloud_quota", ["账号的 Steam 云存储（用于创意工坊文件）已满。", "帳號的 Steam 雲端空間（用於工作坊檔案）已滿。", "アカウントのSteamクラウド（ワークショップ用）の容量がいっぱいです。", "계정의 Steam 클라우드(창작마당용) 공간이 가득 찼습니다.", "Der Steam-Cloud-Speicher des Kontos für Workshop-Dateien ist voll.", "L'espace Steam Cloud du compte pour le Workshop est plein.", "El espacio de Steam Cloud de la cuenta para el Workshop está lleno.", "Место Steam Cloud для файлов мастерской заполнено."]),
    ("c.banned", ["这个账号有封禁（VAC、游戏封禁或创意工坊封禁），无法向这个游戏上传。", "這個帳號有封鎖（VAC、遊戲封鎖或工作坊封鎖），無法向這個遊戲上傳。", "アカウントにBAN（VAC・ゲーム・ワークショップ）があり、このゲームにアップロードできません。", "계정에 차단(VAC, 게임, 창작마당)이 있어 이 게임에 업로드할 수 없습니다.", "Das Konto hat eine Sperre (VAC-, Spiel- oder Workshop-Sperre), die Uploads für dieses Spiel verhindert.", "Le compte a un bannissement (VAC, jeu ou Workshop) qui empêche d'envoyer pour ce jeu.", "La cuenta tiene un bloqueo (VAC, de juego o de Workshop) que impide subir a este juego.", "У учётной записи бан (VAC, игровой или мастерской), он запрещает загрузки для этой игры."]),
    ("c.restricted", ["账号受到限制：社区中心封禁、账号锁定或社区封禁。", "帳號受到限制：社群中心封鎖、帳號鎖定或社群封鎖。", "アカウントが制限されています（ハブBAN・アカウントロック・コミュニティBAN）。", "계정이 제한되었습니다(허브 차단, 계정 잠금, 커뮤니티 차단).", "Das Konto ist eingeschränkt: Hub-Sperre, Kontosperre oder Community-Sperre.", "Le compte est restreint : bannissement du hub, verrouillage ou bannissement communautaire.", "La cuenta está restringida: bloqueo del centro, de cuenta o de comunidad.", "Учётная запись ограничена: бан хаба, блокировка или бан сообщества."]),
    ("c.limited_account", ["受限的 Steam 账号（在 Steam 上消费未满 5 美元）可能不能发布。", "受限的 Steam 帳號（在 Steam 上消費未滿 5 美元）可能不能發佈。", "制限付きアカウント（Steamでの購入が5ドル未満）は公開できない場合があります。", "제한된 계정(Steam에서 5달러 미만 사용)은 게시하지 못할 수 있습니다.", "Ein eingeschränktes Konto (unter 5 USD bei Steam ausgegeben) darf evtl. nicht veröffentlichen.", "Un compte limité (moins de 5 USD dépensés sur Steam) peut ne pas pouvoir publier.", "Una cuenta limitada (menos de 5 USD gastados en Steam) puede no poder publicar.", "Ограниченная учётная запись (потрачено меньше 5 USD) может не иметь права публиковать."]),
    ("c.recent_change", ["账号最近改过密码或邮箱：Steam 会暂停新上传几天（通常 5 天，不活跃账号最长 30 天）。", "帳號最近改過密碼或電子郵件：Steam 會暫停新上傳幾天（通常 5 天，不活躍帳號最長 30 天）。", "最近パスワードかメールを変更したため、Steamが数日間アップロードを止めています（通常5日、最長30日）。", "최근 비밀번호나 이메일을 바꿔 Steam이 며칠간 업로드를 막습니다(보통 5일, 최대 30일).", "Passwort oder E-Mail wurden kürzlich geändert: Steam sperrt neue Uploads einige Tage (5, bei inaktiven Konten bis 30).", "Le mot de passe ou l'e-mail a changé récemment : Steam bloque les envois quelques jours (5, jusqu'à 30).", "Se cambió hace poco la contraseña o el correo: Steam bloquea subidas unos días (5, hasta 30).", "Недавно меняли пароль или e-mail: Steam блокирует загрузки на несколько дней (обычно 5, до 30)."]),
    ("c.already_uploaded", ["同样的上传已经成功过；条目已是最新。", "同樣的上傳已經成功過；項目已是最新。", "同じアップロードは既に成功しており、アイテムは最新です。", "같은 업로드가 이미 성공해 항목이 최신입니다.", "Derselbe Upload ging schon durch; der Eintrag ist aktuell.", "Le même envoi est déjà passé ; l'objet est à jour.", "La misma subida ya se hizo; el objeto está al día.", "Такая же загрузка уже прошла; предмет актуален."]),
    ("c.duplicate_name", ["你的另一个创意工坊条目已经用了这个标题。", "你的另一個工作坊項目已經用了這個標題。", "別のアイテムが既にこのタイトルを使っています。", "다른 항목이 이미 이 제목을 쓰고 있습니다.", "Ein anderer deiner Einträge trägt schon diesen Titel.", "Un autre de vos objets porte déjà ce titre.", "Otro de tus objetos ya usa este título.", "Другой ваш предмет уже носит этот заголовок."]),
    ("c.not_logged_on", ["Steam 客户端掉线了，或账号在另一台电脑上登录了。", "Steam 用戶端掉線了，或帳號在另一台電腦上登入。", "Steamクライアントがサインアウトしたか、別のPCでサインインしました。", "Steam 클라이언트 로그인이 풀렸거나 다른 PC에서 로그인했습니다.", "Der Steam-Client hat die Anmeldung verloren, oder das Konto ist an einem anderen PC angemeldet.", "Le client Steam a perdu sa connexion, ou le compte s'est connecté ailleurs.", "El cliente de Steam perdió la sesión o la cuenta se conectó en otro equipo.", "Клиент Steam потерял вход, или учётная запись вошла на другом ПК."]),
    ("c.steam_side", ["Steam 服务器或网络出了问题；模组本身没有问题。", "Steam 伺服器或網路出了問題；模組本身沒有問題。", "Steamのサーバーかネットワークの問題で、MOD自体には問題ありません。", "Steam 서버나 네트워크 문제이며 모드에는 문제가 없습니다.", "Steams Server oder das Netz hatten ein Problem; am Mod liegt es nicht.", "Les serveurs de Steam ou le réseau ont eu un problème ; le mod n'y est pour rien.", "Fallaron los servidores de Steam o la red; el mod no tiene nada mal.", "Проблема на серверах Steam или в сети; с модом всё в порядке."]),
    ("c.disk_full", ["Steam 存放文件的磁盘已满。", "Steam 存放檔案的磁碟已滿。", "Steamがファイルを置くディスクがいっぱいです。", "Steam이 파일을 두는 디스크가 가득 찼습니다.", "Der Datenträger, auf dem Steam seine Dateien hat, ist voll.", "Le disque où Steam garde ses fichiers est plein.", "El disco donde Steam guarda sus archivos está lleno.", "Диск, где Steam хранит файлы, заполнен."]),
    ("c.item_gone", ["条目 {0} 不存在（已删除）、属于其他游戏，或这个账号无权编辑。", "項目 {0} 不存在（已刪除）、屬於其他遊戲，或這個帳號無權編輯。", "アイテム {0} が存在しない（削除済み）、別のゲームのもの、または編集権限がありません。", "항목 {0}이(가) 없거나(삭제됨), 다른 게임의 것이거나, 이 계정에 편집 권한이 없습니다.", "Eintrag {0} existiert nicht (gelöscht), gehört zu einem anderen Spiel, oder dieses Konto darf ihn nicht bearbeiten.", "L'objet {0} n'existe pas (supprimé), est d'un autre jeu, ou ce compte ne peut pas le modifier.", "El objeto {0} no existe (borrado), es de otro juego o esta cuenta no puede editarlo.", "Предмета {0} нет (удалён), он из другой игры или эта учётная запись не может его менять."]),
    ("c.item_hidden", ["Steam 也不公开显示条目 {0}：它可能已被删除。", "Steam 也不公開顯示項目 {0}：它可能已被刪除。", "アイテム {0} は公開表示もされていないため、削除された可能性があります。", "항목 {0}이(가) 공개로도 보이지 않아 삭제되었을 수 있습니다.", "Steam zeigt Eintrag {0} auch nicht öffentlich: er wurde vielleicht gelöscht.", "Steam n'affiche pas non plus l'objet {0} : il a peut-être été supprimé.", "Steam tampoco muestra el objeto {0}: puede haberse borrado.", "Steam не показывает и предмет {0}: возможно, он удалён."]),
    ("c.title_rejected", ["Steam 拒绝了标题：超过 128 个 UTF-8 字节，或含有它不接受的字符。", "Steam 拒絕了標題：超過 128 個 UTF-8 位元組，或含有它不接受的字元。", "タイトルが拒否されました：128 UTF-8バイト超か、使えない文字があります。", "제목이 거부되었습니다: 128 UTF-8 바이트를 넘거나 받지 않는 문자가 있습니다.", "Steam lehnte den Titel ab: über 128 UTF-8-Bytes oder mit unzulässigen Zeichen.", "Steam a refusé le titre : plus de 128 octets UTF-8 ou caractères non acceptés.", "Steam rechazó el título: más de 128 bytes UTF-8 o caracteres no admitidos.", "Steam отклонил заголовок: больше 128 байт UTF-8 или недопустимые символы."]),
    ("c.content_rejected", ["Steam 拒绝了内容文件夹：路径不是它能读取的文件夹。", "Steam 拒絕了內容資料夾：路徑不是它能讀取的資料夾。", "コンテンツフォルダーが拒否されました：Steamが読めるフォルダーではありません。", "콘텐츠 폴더가 거부되었습니다: Steam이 읽을 수 있는 폴더가 아닙니다.", "Steam lehnte den Inhaltsordner ab: der Pfad ist kein Ordner, den es lesen kann.", "Steam a refusé le dossier de contenu : ce n'est pas un dossier qu'il peut lire.", "Steam rechazó la carpeta de contenido: no es una carpeta que pueda leer.", "Steam отклонил папку содержимого: это не папка, которую он может прочитать."]),
    ("c.preview_rejected", ["Steam 拒绝了预览图的路径。", "Steam 拒絕了預覽圖的路徑。", "プレビュー画像のパスが拒否されました。", "미리보기 경로가 거부되었습니다.", "Steam lehnte den Pfad des Vorschaubilds ab.", "Steam a refusé le chemin de l'aperçu.", "Steam rechazó la ruta de la vista previa.", "Steam отклонил путь к превью."]),
    ("c.no_answer", ["Steam 没有回应：服务器可能很慢，或网络断了。", "Steam 沒有回應：伺服器可能很慢，或網路中斷。", "Steamの応答がありません。サーバーが遅いかネットワークが切れました。", "Steam이 응답하지 않았습니다. 서버가 느리거나 네트워크가 끊겼습니다.", "Steam antwortete nicht: die Server sind langsam, oder das Netz brach ab.", "Steam n'a pas répondu : serveurs lents ou réseau coupé.", "Steam no respondió: servidores lentos o red caída.", "Steam не ответил: медленные серверы или обрыв сети."]),
    ("c.preview_problem", ["失败发生在发送预览图时：最可能是图片的问题（格式、大小或文件损坏）。", "失敗發生在傳送預覽圖時：最可能是圖片的問題（格式、大小或檔案損毀）。", "プレビュー送信中に失敗しました。画像（形式・サイズ・破損）が最も疑わしいです。", "미리보기 전송 중 실패했습니다. 그림(형식, 크기, 손상)이 가장 의심됩니다.", "Es scheiterte beim Senden des Vorschaubilds: am wahrscheinlichsten liegt es am Bild (Format, Größe, defekte Datei).", "L'échec a eu lieu à l'envoi de l'aperçu : l'image est la cause probable (format, taille, fichier abîmé).", "Falló al enviar la vista previa: lo más probable es la imagen (formato, tamaño o archivo dañado).", "Сбой при отправке превью: скорее всего, дело в картинке (формат, размер, повреждение)."]),
    ("c.content_problem", ["失败发生在准备或发送文件时：最可能是某个文件无法读取（被占用、路径过长或含特殊字符）。", "失敗發生在準備或傳送檔案時：最可能是某個檔案無法讀取（被占用、路徑過長或含特殊字元）。", "ファイルの準備・送信中に失敗しました。読めないファイル（使用中・長すぎるパス・特殊文字）が最も疑わしいです。", "파일 준비·전송 중 실패했습니다. 읽을 수 없는 파일(사용 중, 너무 긴 경로, 특수 문자)이 가장 의심됩니다.", "Es scheiterte beim Vorbereiten oder Senden der Dateien: am wahrscheinlichsten ist eine unlesbare Datei (in Benutzung, sehr langer Pfad, seltsame Zeichen).", "L'échec a eu lieu en préparant ou envoyant les fichiers : un fichier illisible (ouvert ailleurs, chemin très long, caractères spéciaux) est probable.", "Falló al preparar o enviar los archivos: lo más probable es un archivo ilegible (en uso, ruta larga, caracteres raros).", "Сбой при подготовке или отправке файлов: вероятно, какой-то файл нельзя прочитать (занят, длинный путь, странные символы)."]),
    ("c.generic", ["Steam 对这个错误码不给原因；很多时候是暂时性的。", "Steam 對這個錯誤碼不給原因；很多時候是暫時性的。", "このコードには理由が示されません。一時的なことが多いです。", "이 코드에는 이유가 없으며, 일시적인 경우가 많습니다.", "Steam nennt für diesen Code keinen Grund; oft ist es vorübergehend.", "Steam ne donne pas de raison pour ce code ; c'est souvent passager.", "Steam no da motivo para este código; a menudo es pasajero.", "Steam не объясняет этот код; часто это временно."]),
    // ---- what to do
    ("f.start_steam", ["启动 Steam，登录拥有群星的账号，然后重试。", "啟動 Steam，登入擁有群星的帳號，然後重試。", "Steamを起動し、Stellarisを所有するアカウントでサインインして再試行してください。", "Steam을 실행하고 Stellaris가 있는 계정으로 로그인한 뒤 다시 시도하세요.", "Steam starten, mit dem Konto anmelden, dem Stellaris gehört, und erneut versuchen.", "Lancez Steam, connectez le compte qui possède Stellaris et réessayez.", "Abre Steam, inicia sesión con la cuenta que tiene Stellaris y reintenta.", "Запустите Steam, войдите в аккаунт со Stellaris и повторите."]),
    ("f.ask_contributor", ["请条目所有者把你的账号加为贡献者（条目页面：所有者控制 → 添加/移除贡献者），或者作为新条目上传。", "請項目擁有者把你的帳號加為貢獻者（項目頁面：擁有者控制 → 新增/移除貢獻者），或作為新項目上傳。", "所有者に協力者として追加してもらう（アイテムページ：所有者コントロール → 協力者の追加/削除）か、新しいアイテムとしてアップロードしてください。", "소유자에게 기여자로 추가해 달라고 하거나(항목 페이지: 소유자 관리 → 기여자 추가/제거), 새 항목으로 업로드하세요.", "Den Besitzer bitten, dein Konto als Mitwirkenden einzutragen (Seite des Eintrags: Besitzersteuerung → Mitwirkende), oder als neuen Eintrag hochladen.", "Demandez au propriétaire de vous ajouter comme contributeur (page de l'objet : Contrôles du propriétaire → Contributeurs), ou publiez un nouvel objet.", "Pide al dueño que añada tu cuenta como colaborador (página del objeto: Controles del propietario → Colaboradores) o súbelo como objeto nuevo.", "Попросите владельца добавить вас в соавторы (страница предмета: Управление владельца → Соавторы) или загрузите как новый предмет."]),
    ("f.accept_agreement", ["打开 Steam 创意工坊法律协议并接受（下方按钮），然后重试。", "開啟 Steam 工作坊法律協議並接受（下方按鈕），然後重試。", "Steamワークショップ法的同意書を開いて同意し（下のボタン）、再試行してください。", "Steam 창작마당 법적 동의서를 열어 동의한 뒤(아래 버튼) 다시 시도하세요.", "Die rechtliche Vereinbarung des Steam Workshop öffnen und annehmen (Knopf unten), dann erneut versuchen.", "Ouvrez l'accord juridique du Workshop Steam et acceptez-le (bouton ci-dessous), puis réessayez.", "Abre el acuerdo legal del Workshop de Steam y acéptalo (botón abajo); luego reintenta.", "Откройте соглашение мастерской Steam и примите его (кнопка ниже), затем повторите."]),
    ("f.check_fields", ["缩短标题和更新说明，只用创意工坊提供的标签，然后重试。", "縮短標題和更新說明，只用工作坊提供的標籤，然後重試。", "タイトルと変更内容を短くし、ワークショップのタグだけを使って再試行してください。", "제목과 변경 사항을 줄이고 창작마당 태그만 써서 다시 시도하세요.", "Titel und Notiz kürzen, nur die Workshop-Tags verwenden, dann erneut versuchen.", "Raccourcissez le titre et la note, gardez les tags du Workshop, puis réessayez.", "Acorta el título y la nota, usa solo las etiquetas del Workshop y reintenta.", "Сократите заголовок и описание, оставьте только теги мастерской и повторите."]),
    ("f.check_paths", ["确认模组文件夹和 thumbnail.png 在描述文件所写的位置，且没有其他程序在写入它们。", "確認模組資料夾和 thumbnail.png 在描述檔所寫的位置，且沒有其他程式在寫入。", "MODフォルダーと thumbnail.png が descriptor の通りの場所にあり、他のプログラムが書き込んでいないか確認してください。", "모드 폴더와 thumbnail.png가 디스크립터대로 있고, 다른 프로그램이 쓰고 있지 않은지 확인하세요.", "Prüfen, dass Mod-Ordner und thumbnail.png dort liegen, wo die Beschreibung sagt, und kein anderes Programm hineinschreibt.", "Vérifiez que le dossier et thumbnail.png sont là où le dit le descripteur, et qu'aucun autre programme n'y écrit.", "Comprueba que la carpeta y thumbnail.png estén donde dice el descriptor y que ningún programa escriba en ellos.", "Проверьте, что папка и thumbnail.png там, где указано в дескрипторе, и что их не пишет другая программа."]),
    ("f.free_cloud", ["删除或缩小一些创意工坊条目或 Steam 云存档，然后重试。", "刪除或縮小一些工作坊項目或 Steam 雲端存檔，然後重試。", "ワークショップのアイテムやクラウドセーブを削除・縮小してから再試行してください。", "창작마당 항목이나 클라우드 저장을 지우거나 줄인 뒤 다시 시도하세요.", "Einige Workshop-Einträge oder Cloud-Spielstände löschen oder verkleinern, dann erneut versuchen.", "Supprimez ou réduisez des objets du Workshop ou des sauvegardes Cloud, puis réessayez.", "Borra o reduce objetos del Workshop o guardados en la nube y reintenta.", "Удалите или уменьшите часть предметов мастерской или облачных сохранений и повторите."]),
    ("f.support", ["只有 Steam 客服能解除；启动器无法绕过。", "只有 Steam 客服能解除；啟動器無法繞過。", "解除できるのはSteamサポートだけで、ランチャーでは回避できません。", "Steam 고객 지원만 풀 수 있으며 런처로는 우회할 수 없습니다.", "Das kann nur der Steam-Support aufheben; der Launcher kann es nicht umgehen.", "Seul le support Steam peut lever cela ; le lanceur ne peut pas le contourner.", "Solo el soporte de Steam puede quitarlo; el lanzador no puede evitarlo.", "Снять это может только поддержка Steam; лаунчер это не обойдёт."]),
    ("f.wait_days", ["等 Steam 解除限制（账号页面会说明），然后重试。", "等 Steam 解除限制（帳號頁面會說明），然後重試。", "Steamの制限が解除されるまで待ってから（アカウントページに表示）再試行してください。", "Steam이 제한을 풀 때까지(계정 페이지 참고) 기다렸다가 다시 시도하세요.", "Warten, bis Steam die Sperre aufhebt (steht auf der Kontoseite), dann erneut versuchen.", "Attendez que Steam lève la restriction (indiqué sur la page du compte), puis réessayez.", "Espera a que Steam quite la restricción (lo indica tu cuenta) y reintenta.", "Дождитесь снятия ограничения (указано на странице аккаунта) и повторите."]),
    ("f.open_item", ["打开条目页面查看现在的版本。", "開啟項目頁面查看現在的版本。", "アイテムページを開いて現在のバージョンを確認してください。", "항목 페이지를 열어 현재 버전을 확인하세요.", "Die Seite des Eintrags öffnen, um die aktuelle Version zu sehen.", "Ouvrez la page de l'objet pour voir sa version.", "Abre la página del objeto para ver la versión actual.", "Откройте страницу предмета, чтобы увидеть текущую версию."]),
    ("f.rename", ["修改模组名称，或改为更新已有条目（填入它的编号）。", "修改模組名稱，或改為更新已有項目（填入它的編號）。", "MOD名を変えるか、既存アイテムの更新にしてください（番号を入力）。", "모드 이름을 바꾸거나 기존 항목을 업데이트하세요(번호 입력).", "Den Namen des Mods ändern oder stattdessen den vorhandenen Eintrag aktualisieren (Nummer eintragen).", "Changez le nom du mod, ou mettez plutôt à jour l'objet existant (tapez son numéro).", "Cambia el nombre del mod o actualiza el objeto existente (escribe su número).", "Измените название мода или обновите существующий предмет (введите номер)."]),
    ("f.retry_later", ["过几分钟再试。", "過幾分鐘再試。", "数分後にもう一度試してください。", "몇 분 뒤 다시 시도하세요.", "In ein paar Minuten erneut versuchen.", "Réessayez dans quelques minutes.", "Inténtalo de nuevo en unos minutos.", "Повторите через несколько минут."]),
    ("f.clear_id", ["如果条目已被删除，从描述文件里删掉 remote_file_id（或清空条目编号），作为新条目上传。", "如果項目已被刪除，從描述檔中刪掉 remote_file_id（或清空項目編號），作為新項目上傳。", "アイテムが削除済みなら、descriptor から remote_file_id を消して（または番号を空にして）新規アップロードしてください。", "항목이 삭제되었다면 디스크립터에서 remote_file_id를 지우고(또는 번호를 비우고) 새 항목으로 올리세요.", "Wurde der Eintrag gelöscht: remote_file_id aus den Beschreibungen entfernen (oder die Nummer leeren) und neu hochladen.", "Si l'objet a été supprimé, retirez remote_file_id des descripteurs (ou videz le numéro) pour publier un nouvel objet.", "Si el objeto se borró, quita remote_file_id de los descriptores (o vacía el número) y súbelo como nuevo.", "Если предмет удалён, уберите remote_file_id из дескрипторов (или очистите номер) и загрузите как новый."]),
    ("f.shorten_title", ["缩短模组名称后重试。", "縮短模組名稱後重試。", "MOD名を短くして再試行してください。", "모드 이름을 줄이고 다시 시도하세요.", "Den Namen des Mods kürzen und erneut versuchen.", "Raccourcissez le nom du mod et réessayez.", "Acorta el nombre del mod y reintenta.", "Сократите название мода и повторите."]),
    ("f.fix_preview", ["把 thumbnail.png 重新存成小于 1 MB 的 PNG 或 JPG 后重试。", "把 thumbnail.png 重新存成小於 1 MB 的 PNG 或 JPG 後重試。", "thumbnail.png を1MB未満のPNGかJPGで保存し直して再試行してください。", "thumbnail.png를 1MB 미만의 PNG나 JPG로 다시 저장한 뒤 시도하세요.", "thumbnail.png neu als PNG oder JPG unter 1 MB speichern und erneut versuchen.", "Réenregistrez thumbnail.png en PNG ou JPG de moins de 1 Mo, puis réessayez.", "Vuelve a guardar thumbnail.png como PNG o JPG de menos de 1 MB y reintenta.", "Пересохраните thumbnail.png как PNG или JPG меньше 1 МБ и повторите."]),
    ("f.copy_report", ["如果一直失败，复制诊断报告发给帮你的人。", "如果一直失敗，複製診斷報告傳給幫你的人。", "失敗が続く場合は、診断レポートをコピーして手伝ってくれる人に送ってください。", "계속 실패하면 진단 보고서를 복사해 도와줄 사람에게 보내세요.", "Wenn es weiter scheitert: den Diagnosebericht kopieren und an deine Hilfe schicken.", "Si l'échec persiste, copiez le rapport de diagnostic et envoyez-le à qui vous aide.", "Si sigue fallando, copia el informe de diagnóstico y envíalo a quien te ayude.", "Если сбой повторяется, скопируйте отчёт и отправьте тому, кто помогает."]),
    ("f.created_item", ["失败前已创建条目 {0}（私密），它的编号已写入描述文件：重试会更新它，不会再新建一个。", "失敗前已建立項目 {0}（私人），編號已寫入描述檔：重試會更新它，不會再新建一個。", "失敗前にアイテム {0}（非公開）が作成され、番号は descriptor に書き込まれました。再試行すると新規作成ではなく更新になります。", "실패 전에 항목 {0}(비공개)이(가) 만들어졌고 번호가 디스크립터에 기록되었습니다. 다시 시도하면 새로 만들지 않고 업데이트합니다.", "Vor dem Fehler wurde Eintrag {0} angelegt (privat), seine Nummer steht in den Beschreibungen: ein neuer Versuch aktualisiert ihn statt einen weiteren anzulegen.", "L'objet {0} a été créé avant l'échec (privé) et son numéro est dans les descripteurs : réessayer le mettra à jour au lieu d'en créer un autre.", "Antes del fallo se creó el objeto {0} (privado) y su número está en los descriptores: al reintentar se actualiza en vez de crear otro.", "До сбоя создан предмет {0} (скрытый), его номер записан в дескрипторы: повтор обновит его, а не создаст новый."]),
];

/// A key's words in a language, with its values in place; values that are keys themselves (a step, a phase) are put in as their words.
pub fn text(lang: Lang, key: &str, args: &[String]) -> String {
    let idx = match lang {
        Lang::En => None,
        Lang::ZhHans => Some(0),
        Lang::ZhHant => Some(1),
        Lang::Ja => Some(2),
        Lang::Ko => Some(3),
        Lang::De => Some(4),
        Lang::Fr => Some(5),
        Lang::Es => Some(6),
        Lang::Ru => Some(7),
    };
    let template = |k: &str| -> Option<String> {
        match idx {
            Some(i) => T.iter().find(|(kk, _)| *kk == k).map(|(_, v)| v[i].to_string()),
            None => Some(uploadcheck::english(k).to_string()).filter(|s| !s.is_empty()),
        }
    };
    let mut s = template(key).unwrap_or_else(|| uploadcheck::text(key, args));
    for (i, a) in args.iter().enumerate() {
        let v = if a.contains('.') && !a.contains(' ') { template(a).unwrap_or_else(|| a.clone()) } else { a.clone() };
        s = s.replace(&format!("{{{i}}}"), &v);
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn holes(s: &str) -> Vec<String> {
        let mut v: Vec<String> = (0..4).map(|i| format!("{{{i}}}")).filter(|h| s.contains(h.as_str())).collect();
        v.sort();
        v
    }

    #[test]
    fn every_key_in_every_language_with_the_same_values() {
        for key in uploadcheck::KEYS {
            let row = T.iter().find(|(k, _)| k == key).unwrap_or_else(|| panic!("{key} has no translations"));
            let want = holes(uploadcheck::english(key));
            for (i, t) in row.1.iter().enumerate() {
                assert!(!t.is_empty(), "{key} [{i}] is empty");
                assert_eq!(holes(t), want, "{key} [{i}]: {t}");
            }
        }
        assert_eq!(T.len(), uploadcheck::KEYS.len(), "a translation without a key");
        // a step inside a headline is put in as its words
        assert_eq!(text(Lang::ZhHans, "ex.headline", &["ex.at_title".into()]), "上传在设置标题时中断。");
        assert_eq!(text(Lang::En, "pf.summary", &["3".into(), "1 KB".into()]), "3 files, 1 KB will be uploaded.");
    }
}
