[package]
name = "stl-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "stl"
path = "src/main.rs"

[dependencies]
stl-core = { path = "../stl-core" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }

[build-dependencies]
embed-resource = "3"
